INSERT INTO city (name) VALUES
('New York'),
('Los Angeles'),
('Chicago'),
('Houston'),
('Phoenix'),
('Philadelphia'),
('San Antonio'),
('San Diego'),
('Dallas'),
('San Jose'),
('Austin'),
('Jacksonville'),
('Fort Worth'),
('Columbus'),
('Charlotte'),
('San Francisco'),
('Indianapolis'),
('Seattle'),
('Denver'),
('Washington'),
('Boston'),
('El Paso'),
('Detroit'),
('Nashville'),
('Portland'),
('Memphis'),
('Oklahoma City'),
('Las Vegas'),
('Louisville'),
('Baltimore'),
('Milwaukee'),
('Albuquerque'),
('Tucson'),
('Fresno'),
('Sacramento'),
('Mesa'),
('Atlanta'),
('Kansas City'),
('Colorado Springs'),
('Miami'),
('Raleigh'),
('Omaha'),
('Long Beach'),
('Virginia Beach'),
('Oakland'),
('Minneapolis'),
('Tampa'),
('Arlington'),
('New Orleans'),
('Wichita'),
('Cleveland'),
('Bakersfield'),
('Aurora'),
('Anaheim'),
('Honolulu'),
('Santa Ana'),
('Riverside'),
('Corpus Christi'),
('Lexington'),
('Stockton'),
('Henderson'),
('Saint Paul'),
('St. Louis'),
('Cincinnati'),
('Pittsburgh'),
('Greensboro'),
('Anchorage'),
('Plano'),
('Lincoln'),
('Orlando'),
('Irvine'),
('Newark'),
('Durham'),
('Chula Vista'),
('Toledo'),
('Fort Wayne'),
('St. Petersburg'),
('Laredo'),
('Jersey City'),
('Chandler'),
('Madison'),
('Lubbock'),
('Scottsdale'),
('Reno'),
('Buffalo'),
('Gilbert'),
('Glendale'),
('North Las Vegas'),
('Winston-Salem'),
('Chesapeake'),
('Norfolk'),
('Fremont'),
('Garland'),
('Irving'),
('Hialeah'),
('Richmond'),
('Boise'),
('Spokane'),
('Baton Rouge'),
('Des Moines'),
('Modesto'),
('Birmingham'),
('Tacoma'),
('Fontana'),
('Rochester'),
('Oxnard'),
('Moreno Valley'),
('Fayetteville'),
('Aurora'),
('Glendale'),
('Yonkers'),
('Huntington Beach'),
('Montgomery'),
('Amarillo'),
('Little Rock'),
('Akron'),
('Columbus'),
('Augusta'),
('Grand Rapids'),
('Shreveport'),
('Salt Lake City'),
('Huntsville'),
('Mobile'),
('Tallahassee'),
('Grand Prairie'),
('Overland Park'),
('Knoxville'),
('Worcester'),
('Brownsville'),
('Tempe'),
('Santa Clarita'),
('Newport News'),
('Cape Coral'),
('Providence'),
('Fort Lauderdale'),
('Chattanooga'),
('Rancho Cucamonga'),
('Oceanside'),
('Santa Rosa'),
('Garden Grove'),
('Vancouver'),
('Sioux Falls'),
('Ontario'),
('McKinney'),
('Elk Grove'),
('Jackson'),
('Pembroke Pines'),
('Salem'),
('Springfield'),
('Corona'),
('Eugene'),
('Fort Collins'),
('Hayward'),
('Lancaster'),
('Alexandria'),
('Salinas'),
('Palmdale'),
('Lakewood'),
('Springfield'),
('Sunnyvale'),
('Hollywood'),
('Pasadena'),
('Clarksville'),
('Pomona'),
('Kansas City'),
('Macon'),
('Escondido'),
('Paterson'),
('Joliet'),
('Naperville'),
('Rockford'),
('Savannah'),
('Bridgeport'),
('Torrance'),
('Sydney');
